BAU Snyk vulnerability in hibernate-validator
Address a vulnerability indicated in https://snyk.io/vuln/SNYK-JAVA-ORGHIBERNATE-568162

Cannot be applied to `configurations.all` as it results in NoClassDefFoundErrors.

The better solution is to upgrade to Dropwizard 2 whih omits the vuln, but this is not a smooth migration.